name = "invaders-78"
compatibility_date = "2026-07-28"
pages_build_output_dir = "dist"

[[kv_namespaces]]
binding = "HI_SCORE"
id = "6c3aa83859344ae9af9dec3401249cad"
preview_id = "c764675840bd4784b8eda943aaf3e652"
